# Generated by Django 5.1 on 2024-08-14 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
