# Generated by Django 5.1 on 2024-08-15 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
    ]
